AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-python3.7

  Sample SAM Template for lambda-python3.7

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  MAnewsStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/statemachine.asl.json
      DefinitionSubstitutions:
        ScrapperFunctionArn: !GetAtt ScrapperFunction.Arn
        CombinorFunctionArn: !GetAtt CombinorFunction.Arn
        KickoffFunctionArn: !GetAtt KickoffFunction.Arn
      Events:
        WeeklyReportSchedule:
          Type: Schedule # More info about Schedule Event Source: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-schedule.html
          Properties:
            Description: Trigger the report machine to run every Monday at 9 am EST
            Enabled: True # This schedule is disabled by default to avoid incurring charges.
            Schedule: 'cron(0 14 ? * MON *)'

      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref ScrapperFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref CombinorFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref KickoffFunction

  ChromiumLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: chromium-selenium-layer
      Description: Headless Chromium and Selenium WebDriver
      ContentUri: layers/selenium-binaries
      CompatibleRuntimes:
        - python3.7
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain
  
  PythonDepLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: selenium-layer
      Description: Selenium, Requests, Chromedriver-binary
      ContentUri: layers/python-dependencies
      CompatibleRuntimes:
        - python3.7
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain
      
  ScrapperFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ma_trigger/
      Handler: scrapper.scrape_website
      Runtime: python3.7
      MemorySize: 2500
      Timeout: 100
      Layers:
        - !Ref ChromiumLayer
        - !Ref PythonDepLayer
      Environment:
        Variables:
          CLEAR_TMP: "true"
          PATH: /var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin:/tmp/bin:/tmp/bin/lib     
  CombinorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: combinor/
      Handler: combinor.combinor
      Runtime: python3.7
  KickoffFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: kickoff/
      Handler: kickoff.kickoff
      Runtime: python3.7


Outputs:
  ScrapperFunction:
    Description: "Webscrapping Lambda Function ARN"
    Value: !GetAtt ScrapperFunction.Arn
  ScrapperFunctionIamRole:
    Description: "Implicit IAM Role created for Webscrapping function"
    Value: !GetAtt ScrapperFunctionRole.Arn
  CombinorFunction:
    Description: "Combine scrappers Lambda Function ARN"
    Value: !GetAtt CombinorFunction.Arn
  CombinorFunctionIamRole:
    Description: "Implicit IAM Role created for Webscrapping function"
    Value: !GetAtt ScrapperFunctionRole.Arn
  KickoffFunction:
    Description: "Webscrapping Lambda Function ARN"
    Value: !GetAtt KickoffFunction.Arn
  KickoffFunctionIamRole:
    Description: "Implicit IAM Role created for Webscrapping function"
    Value: !GetAtt KickoffFunctionRole.Arn

